import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  // Connector for MM
  // Import web3 lib
  // Observe/watch for connect/login

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className="flex flex-col items-center justify-center min-h-screen py-2 bg-slate-100">
          <button
            className="px-4 py-2 rounded-md bg-purple-600 cursor-pointer hover:bg-purple-500 text-xl font-semibold duration-100 text-white"
          >
            Connect Wallet
          </button>
        </div>
      </body>

    </div>
  )
}

export default Home
